### ISSUE TITLE
NotImplementedError: unknown query query

### ISSUE THREAD

**Issue by eN0Rm** [20c/rdap#2]
```
$ rdap query vg.no 
Traceback (most recent call last):
  File "/home/fredrik/.local/bin/rdap", line 11, in <module>
    sys.exit(main())
  File "/home/fredrik/.local/lib/python3.6/site-packages/rdap/__main__.py", line 59, in main
    data = client.get(each).parsed()
  File "/home/fredrik/.local/lib/python3.6/site-packages/rdap/client.py", line 139, in get
    raise NotImplementedError("unknown query {}".format(query))
NotImplementedError: unknown query query
```
My config.yaml

```
fredrik@normann:~$ cat .rdap/config.yaml 
rdap:
  # URL to bootstrap the initial request off
  bootstrap_url: https://rdap.test.norid.no
  # how to format the output
  output_format: yaml
  # API key for use at rdap.lacnic.net
  lacnic_apikey: None
  # role types to recursively query when processing
  recurse_roles: ["administrative", "technical"]
```

**Comment by grizz** [comment]
@eN0Rm The problem was it didn't even have domain support, should work fine with your config file now, using the following command.

```sh
rdap vg.no
```
