### ISSUE TITLE
Queries beginning with `as` throw exceptions

### ISSUE THREAD

**Issue by seanmarpo** [20c/rdap#24]
Using the default config that points to `rdap.org`, you can run the utility as such:
* `rdap astound.ai` -- An exception will be thrown

```
Traceback (most recent call last):
  File "/Users/smarpo/.local/share/virtualenvs/check-invalid-apps-btF75AhN/bin/rdap", line 8, in <module>
    sys.exit(main())
  File "/Users/smarpo/.local/share/virtualenvs/check-invalid-apps-btF75AhN/lib/python3.9/site-packages/rdap/cli.py", line 77, in main
    obj = client.get(each)
  File "/Users/smarpo/.local/share/virtualenvs/check-invalid-apps-btF75AhN/lib/python3.9/site-packages/rdap/client.py", line 231, in get
    return self.get_asn(qstr[2:])
  File "/Users/smarpo/.local/share/virtualenvs/check-invalid-apps-btF75AhN/lib/python3.9/site-packages/rdap/client.py", line 278, in get_asn
    asn = int(asn)
ValueError: invalid literal for int() with base 10: 'tound.ai'
```

Looks like if your query begins with `as`, you strip it off per: https://github.com/20c/rdap/blob/master/rdap/client.py#L230

Let me know if I'm using your RDAP client incorrectly, but seems like a legit bug to me. Thanks!

**Comment by grizz** [comment]
Definitely a bug, good catch, thanks!

**Comment by grizz** [comment]
@seanmarpo was hoping to get to it today, feel free to PR -- otherwise will get it fixed and released by Monday :)

**Comment by seanmarpo** [comment]
@grizz, thanks for patching this up. Can confirm the latest version works as expected. 👍
